[api]
enabled = true
address = "0.0.0.0:8686"

#[sources.demo_logs]
#type = "demo_logs"
#interval = 1.0
#format = "json"

[sources.lc]
type = "socket"
address = "0.0.0.0:6514"
max_length = 102_400
mode = "tcp"

[transforms.lctransform]
type = "remap"
inputs = ["lc"]
source = """
parsed, err = parse_syslog(.message)
if err == null {
  . |= parsed
}
. = parse_json!(string!(.message))
"""


[transforms.logtail_transform]
type = "remap"
inputs = [ "lc" ]
source = '''
.dt = del(.timestamp)
'''

[sinks.logtail_http_sink]
type = "http"
inputs = [ "logtail_transform" ]
uri = "https://in.logtail.com/"
encoding.codec = "json"
auth.strategy = "bearer"
auth.token = "${LOGTAIL_TOKEN}"

[sinks.console]
inputs = ["logtail_transform"]
target = "stdout"
type = "console"
encoding.codec = "json"
